feature: add config for undefined method
abak-press/slaver pull request #11
Opened 2016-12-27 12:25 UTC by deniskorobicyn

Описание проблема в комментах - https://jira.railsc.ru/browse/PC4-17713

2016-12-27 12:40 UTC, deniskorobicyn commented
@Napolskih можно тут drone активировать?
 прав не хватает...

2016-12-27 16:00 UTC, bibendi requested changes

2016-12-27 16:00 UTC, bibendi commented on .drone.yml
> +      RUBY_IMAGE_TAG: 2.2-1
2.2-2

2016-12-27 16:00 UTC, bibendi commented on .drone.yml
> +    - SPHINX_IMAGE_TAG=2.2
не нужен

2016-12-27 16:00 UTC, bibendi commented on dip.yml
> +  - dip sh ln -sf ../../.bundle/config /app/gemfiles/.bundle/config
олд скул

2016-12-27 16:00 UTC, bibendi commented on docker-compose.yml
> +      - SPHINX_CONFIG_FILE=/sphinx/conf/sphinx.conf
опять же сфинкс не нужен

2016-12-27 16:00 UTC, bibendi commented on lib/slavable.rb
> +    return if options[:allow_undefined] && !(method_names - instance_methods(false)).empty?
мне кажется надо каждый метод проверять, а не выходить, если только одного нет

2016-12-28 09:21 UTC, apress-hound commented on lib/slavable.rb
> +        if (instance_methods.include?(method) || methods.include?(method))
Convert if nested inside else to elsif.<br>Don't use parentheses around the condition of an if.

2016-12-28 09:21 UTC, apress-hound commented on lib/slavable.rb
> +      aliased_method, punctuation = method.to_s.sub(/([?!=])$/, ''), $1
Do not use parallel assignment.<br>Avoid the use of Perl-style backrefs.

2016-12-28 09:21 UTC, apress-hound commented on lib/slavable.rb
> +        aliased_method, punctuation = method.to_s.sub(/([?!=])$/, ''), $1
Do not use parallel assignment.<br>Avoid the use of Perl-style backrefs.

2016-12-28 09:30 UTC, apress-hound commented on lib/slavable.rb
> +      aliased_method, punctuation = method.to_s.sub(/([?!=])$/, ''), $1
Do not use parallel assignment.<br>Avoid the use of Perl-style backrefs.

2016-12-28 09:43 UTC, apress-hound commented on lib/slavable.rb
> +      elsif (instance_methods.include?(method) || methods.include?(method))
Don't use parentheses around the condition of an elsif.

2016-12-28 10:35 UTC, apress-hound commented on lib/slavable.rb
> +      aliased_method, punctuation = method.to_s.sub(/([?!=])$/, ''), $1
Do not use parallel assignment.<br>Avoid the use of Perl-style backrefs.

2016-12-28 10:40 UTC, deniskorobicyn commented
up @bibendi @Napolskih 

заюзал method_added, теперь можно писать switch в любом месте. 

Если метода нет, то как только он объявится его тут же переключит на слейв.

2016-12-28 10:58 UTC, bibendi requested changes

2016-12-28 10:58 UTC, bibendi commented on .drone.yml
> +    - dip ssh add -T
https://github.com/abak-press/apress-traits_auto_binding/blob/master/.drone.yml#L33

2016-12-28 10:58 UTC, bibendi commented on docker-compose.yml
> +      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
https://github.com/abak-press/apress-traits_auto_binding/blob/master/docker-compose.yml#L9

2016-12-28 10:58 UTC, bibendi commented on lib/slavable.rb
> +  module PrivateMethods
название модуля почему такое?

2016-12-28 10:58 UTC, bibendi commented
какой-то рокет сайнс получился.
фигн знает надо ли нам такой потенциальный источник багов )

2016-12-28 11:32 UTC, deniskorobicyn commented on docker-compose.yml
> +      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
зачем? это же публичный гем

2016-12-28 11:36 UTC, bibendi commented on docker-compose.yml
> +      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
что это меняет?

2016-12-28 11:37 UTC, deniskorobicyn commented on docker-compose.yml
> +      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
Ну нам не надо конфигурировать вот это - https://github.com/abak-press/apress-traits_auto_binding/blob/master/dip.yml#L45, он разве для чего-то еще используется?

2016-12-28 11:46 UTC, deniskorobicyn commented on docker-compose.yml
> +      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
воотще я чето не могу понять смысла этой переменной, оно же используется для [глобальной](https://github.com/bundler/bundler/blob/159c7dc8566f9bdd54f6d877658ad29397e2ec67/lib/bundler/settings.rb#L280) конфигурации, а мы ее назначаем на локальную штуку - http://bundler.io/v1.3/bundle_config.html

2016-12-28 11:59 UTC, deniskorobicyn commented
вообщем рокетсайанс выпилил и схоронил в своем форке в отдельной ветке -  https://github.com/deniskorobicyn/slaver/tree/rocketscience_with_switch

Тк и правда очень страшно и сложно)

В проекте по месту ломания сделал проще

```
switch :some_method, to: :slave if method_defined?(:some_method)
```

2016-12-28 12:00 UTC, bibendi commented on docker-compose.yml
> +      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
> Ну нам не надо конфигурировать вот это - https://github.com/abak-press/apress-traits_auto_binding/blob/master/dip.yml#L45

ну если только с этой точки зрения, то да )

ок.

2016-12-28 12:01 UTC, bibendi commented on .drone.yml
> +    - dip ssh add -T -v /ssh_keys -k /ssh_keys/id_rsa
если гем публичный, то и это не надо поидее, мы же не будем ставить приватные гемы

2016-12-28 12:02 UTC, bibendi approved these changes

2016-12-28 12:04 UTC, Napolskih approved these changes

2016-12-28 12:14 UTC, merged